### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by ghost** [vhsantos/centreon_report_to_pdf#1]
how can you add the proxy parameter or ignore ssl

**Comment by vhsantos** [comment]
Hi @spiralemystik ,

Sorry, but I never used it with a proxy and don't thought about it !!! So, actually, the proxy parameters aren't considered in this project. But, it is relative "easy" to implement because the request module from python work well with proxy.
You have 3 options:

1 - Chage the lines in the [centreon_report_to_pdf/Settings.py](https://github.com/vhsantos/centreon_report_to_pdf/blob/e18b9b45f532985f4aa8f9290790169e724d75cb/centreon_report_to_pdf/Settings.py#L448
) to add a proxy for yourself, like this:


```
    # Login and get the session/cookies.
    proxies = {
        'http': 'http://10.10.1.10:3128',
        'https': 'http://10.10.1.10:1080',
    }
    centreon_session = requests.session()
    centreon_session.get(LOGIN_URL)
    centreon_session.proxies.update(proxies)
    
    # Download CSV file
    csv_download = centreon_session.get(url_csv)

```


2 - If you are using linux, you can use/define the proxy environments variables before run the report:
```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

more info about request and proxy here
[request doc](https://requests.readthedocs.io/en/master/user/advanced/#proxies)

3 - You can wait a couple of weeks and I will release a new release with proxy configuration in the settings files !! :-D

Salu2

**Comment by ghost** [comment]
Thanks a lot.
I think my problem comes from the SSL certificate. How can I ignore the verification for self signed certificates?
